crypto_tracker/crypto_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

crypto_tracker/website/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('exchanges/', views.ExchangesListView.as_view(), name='exchanges_list'),
    path('exchanges/<slug:slug>', views.ExchangeDetailView.as_view(), name='exchange_detail'),
    path('news/', views.news, name='news'),
    path('chart/', views.Chart.as_view(), name='chart'),
    path('dashboard/', views.DashboardListView.as_view(), name='dashboard_list'),
    path('dashboard/create', views.DashboardCreateView.as_view(), name='dashboard_create'),
    path('dashboard/<int:pk>', views.DashboardDetailView.as_view(), name='dashboard_detail'),
    path('dashboard/<int:pk>/delete', views.DashboardDeleteView.as_view(), name='dashboard_delete')
]

crypto_tracker/website/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe
import ccxt
from .tasks import test_func, get_price_change
from celery import shared_task
from .functions import CRYPTOGRAPHIC_KEY


class ApiContainer(models.Model):
    exchange = models.CharField(_("exhcange"), choices=((exchange, exchange) for exchange in ccxt.exchanges))
    name = models.CharField(_("name"), max_length=250)
    description = models.TextField(_("description"))
    apikey = models.CharField(_("apikey"), max_length=250)
    secret_key = models.BinaryField(_("secret key"), null=True, blank=True)
    user = models.ForeignKey(get_user_model(), verbose_name=_("user"), on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = _("Api container")
        verbose_name_plural = _("Api containers")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("apicontainer_detail", kwargs={"pk": self.pk})
    

class ExchangeModel(models.Model):
    exchange = models.CharField(_("exchange"), max_length=50)
    slug = models.SlugField(default="", null=False)
    

    def exchange_instance_balance(self, apiKey=None, secret=None):
        if apiKey==None and secret==None:
            return self.exchange_instance
        elif apiKey and secret:
            exchange_class = getattr(ccxt, self.exchange)
            decrypted_secret = CRYPTOGRAPHIC_KEY.decrypt(bytes(secret))
            exchange = exchange_class({'apiKey': apiKey, 'secret': decrypted_secret.decode('UTF-8')})
            exchange.load_markets()
            return exchange.fetch_balance()
    
    @property
    def exchange_instance(self):
        return getattr(ccxt, self.exchange)()
    
    @property
    def exchange_markets(self):
        return self.exchange_instance.load_markets()
    
    def get_price_change(self, period, symbol):
        try:
            task_result = get_price_change.delay(period=period, exchange_name=self.exchange, symbol=symbol)
            price = task_result.get()
        except Exception as e:
            return f"get_price_change: {e}"
        if price['result'].find('-'):
            return mark_safe(f"<p style='color: green'>{price['result']}</p>")
        else:
            return mark_safe(f"<p style='color: red'>{price['result']}</p>")
    
    @property
    def get_markets_with_period_prices(self):
        markets_with_periods = {}
        for market in self.exchange_markets.keys():
            market = market.replace("/", "")
            markets_with_periods[market] = {
                "1h": self.get_price_change(3600000, market), 
                "24h": self.get_price_change(86400000, market),
                "7d": self.get_price_change(604800000, market),
                "30d": self.get_price_change(2592000000, market),
                "365d": self.get_price_change(31536000000, market)
                }
        return markets_with_periods
    
    @property
    def get_info(self):
        return self.exchange_instance.describe
    
    # @shared_task(bind=True)
    def fetch_ohlcv(self, get, symbol, timeframe='1m', since=None, limit=None, params={}):
        all_symbol_current_prices = {}

        try:
            result_instance = self.exchange_instance.fetch_ohlcv(symbol=symbol, timeframe=timeframe, since=since, limit=limit, params=params)[0]
        except Exception as e:
            return f"fetch_ohlcv: {e}"
        all_symbol_current_prices[symbol] = {
            'timestamp': result_instance[0],
            'open': result_instance[1],
            'high': result_instance[2],
            'low': result_instance[3],
            'close': result_instance[4],
            'volume': result_instance[5],
            }
        if get.lower() == 'all':
            return all_symbol_current_prices
        return all_symbol_current_prices[symbol][get]
        #return self.exchange_instance.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=limit, params=params)

    class Meta:
        verbose_name = _("Exchange model")
        verbose_name_plural = _("Exchange models")

    def __str__(self):
        return self.exchange

    def get_absolute_url(self):
        return reverse("ExchangeModel_detail", kwargs={"pk": self.pk})

crypto_tracker/website/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from . import models
import ccxt

# news search form
class NewsSearchBar(forms.Form):
    search = forms.CharField(max_length=250)


class ApiContainerCreateForm(forms.ModelForm):

    secret_key_text = forms.CharField(label=_('secret key'), widget=forms.PasswordInput())
    class Meta:
        model = models.ApiContainer
        fields = ['exchange', 'name', 'apikey', 'secret_key_text', 'user']
        widgets = {
            'user': forms.HiddenInput(),
        }

crypto_tracker/website/views.py
from typing import Any, Dict
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from django.utils.translation import gettext_lazy as _
from . import forms
from . import models
from .functions import sort_time, CRYPTOGRAPHIC_KEY
# Celery stuff
from celery import current_app as app
from django_celery_beat.models import PeriodicTask
from celery.result import AsyncResult
#news stuff (news.html)
from GoogleNews import GoogleNews
# ccxt stuff (chart.html)
import ccxt


# Create your views here.
def index(request):
    # get latest news
    search_terms = ['Crypto', 'Stocks', 'Forex', 'Futures', 'Indices', 'Bonds']
    articles = []
    for term in search_terms:
        news_class = GoogleNews()
        news_class.get_news(term)
        article = news_class.results(sort=False)[0] # neveikia sort funkcija, nes datetime.datetime < float, neiseina lygint
        articles.append(article)

    # get price data (last closed price)
    exchange = ccxt.binance()
    BTCUSDT = exchange.fetch_ohlcv('BTCUSDT', limit=2)[0][4] # BITCOIN / USDT
    ETHUSDT = exchange.fetch_ohlcv('ETHUSDT', limit=2)[0][4] # ETHERIUM / USDT
    BUSDUSDT = exchange.fetch_ohlcv('BUSDUSDT', limit=2)[0][4] # USDOLLAR / USDT
    BNBUSDT = exchange.fetch_ohlcv('BNBUSDT', limit=2)[0][4] # BINANCECOIN / USDT
    USDCUSDT = exchange.fetch_ohlcv('USDCUSDT', limit=2)[0][4] # USDCOIN / USDT

    # BTCUSDT_24h_task = PeriodicTask.objects.filter(name="BTCUSDT")
    # BTCUSDT_24h_result = BTCUSDT_24h_task.first().result if BTCUSDT_24h_task.first().ready() else None

    context = {
        'articles': articles,
        'room_name': 'track',
        'BTCUSDT': {'current': BTCUSDT, 
                    # '1h': BTCUSDT_24h_result,}
                    # '24h': get_price_change.delay(period=86400000, symbol='BTCUSDT'),
                    # '7d': get_price_change.delay(period=604800000, symbol='BTCUSDT'),
                    # '30d': get_price_change.delay(period=2592000000, symbol='BTCUSDT'),
                    # '365d': get_price_change.delay(period=31536000000, symbol='BTCUSDT')
                    },
        'ETHUSDT': {'current': ETHUSDT, 
                    # '1h': get_price_change.delay(period=3600000, symbol='ETHUSDT'), #period=3600000, symbol='ETHUSDT'
                    # '24h': get_price_change.delay(period=86400000, symbol='ETHUSDT'), #period=86400000, symbol='ETHUSDT'
                    # '7d': get_price_change.delay(period=604800000, symbol='ETHUSDT'), #period=604800000, symbol='ETHUSDT'
                    # '30d': get_price_change.delay(period=2592000000, symbol='ETHUSDT'), #period=2592000000, symbol='ETHUSDT'
                    # '365d': get_price_change.delay(period=31536000000, symbol='ETHUSDT') #period=31536000000, symbol='ETHUSDT'
                    },
        'BUSDUSDT': {'current': BUSDUSDT, 
                    # '1h': get_price_change.delay(period=3600000, symbol='BUSDUSDT'),
                    # '24h': get_price_change.delay(period=86400000, symbol='BUSDUSDT'),
                    # '7d': get_price_change.delay(period=604800000, symbol='BUSDUSDT'),
                    # '30d': get_price_change.delay(period=2592000000, symbol='BUSDUSDT'),
                    # '365d': get_price_change.delay(period=31536000000, symbol='BUSDUSDT')
                    },
        'BNBUSDT': {'current': BNBUSDT, 
                    # '1h': get_price_change.delay(period=3600000, symbol='BNBUSDT'),
                    # '24h': get_price_change.delay(period=86400000, symbol='BNBUSDT'),
                    # '7d': get_price_change.delay(period=604800000, symbol='BNBUSDT'),
                    # '30d': get_price_change.delay(period=2592000000, symbol='BNBUSDT'),
                    # '365d': get_price_change.delay(period=31536000000, symbol='BNBUSDT')
                    },
        'USDCUSDT': {'current': USDCUSDT, 
                    # '1h': get_price_change.delay(period=3600000, symbol='USDCUSDT'),
                    # '24h': get_price_change.delay(period=86400000, symbol='USDCUSDT'),
                    # '7d': get_price_change.delay(period=604800000, symbol='USDCUSDT'),
                    # '30d': get_price_change.delay(period=2592000000, symbol='USDCUSDT'),
                    # '365d': get_price_change.delay(period=31536000000, symbol='USDCUSDT')
                    },
    }

    return render(request, 'tracker_site/index.html', context)


def news(request):
    form = forms.NewsSearchBar()
    search = request.GET.get('search')
    sort_option = request.GET.get('sort')
    if search:
        news_class = GoogleNews()
        news_class.get_news(search)
        articles = news_class.results(sort=True) # '<' not supported between instances of 'float' and 'datetime.datetime'
        if sort_option == 'desc':
            articles = articles.sort(key=sort_time)
    else:
        articles = None
    
    context = {
        'articles': articles,
        'form': form,
    }
    return render(request, 'tracker_site/news.html', context)

class ExchangesListView(generic.ListView):
    model = models.ExchangeModel
    template_name = 'tracker_site/exchanges_list.html'
    
    def get_queryset(self):
        sort_option = self.request.GET.get('sort')
        qs = super().get_queryset()
        if sort_option == 'name':
            qs = qs.order_by('exchange')
        return qs
    

class ExchangeDetailView(generic.DeleteView):
    model = models.ExchangeModel
    template_name = 'tracker_site/exchange_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = get_object_or_404(models.ExchangeModel, slug=self.kwargs['slug'])

        context['exchange'] = obj
        context["markets"] = list(obj.exchange_markets.keys())[:3]
        return context
    

class Chart(generic.TemplateView):
    model = models.ExchangeModel
    template_name = 'tracker_site/chart.html'
    success_url = reverse_lazy('chart')

    def get_context_data(self, **kwargs: Any):
        context =  super().get_context_data(**kwargs)
        try:
            obj = get_object_or_404(models.ExchangeModel, exchange=self.request.GET.get('exchange'))
        except:
            obj = get_object_or_404(models.ExchangeModel, exchange='ace')

        
        context = {
            "exchanges": self.model.objects.all(),
            "exchange": self.request.GET.get('exchange'),
            "tradingview_button": "False",
            'markets_list': obj.exchange_markets
            
        }
        return context
    
    
# Dashboard.html views
class DashboardListView(LoginRequiredMixin, generic.ListView):
    model = models.ApiContainer
    template_name = 'tracker_site/dashboard.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs
    

class DashboardDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.ApiContainer
    template_name = 'tracker_site/dashboard_detail.html'
    success_url = reverse_lazy('dashboard_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        api_obj = get_object_or_404(models.ApiContainer, id=self.kwargs['pk'])
        ccxt_obj = get_object_or_404(models.ExchangeModel, exchange=api_obj.exchange)

        context["api_obj"] = api_obj
        context["balance"] = ccxt_obj.exchange_instance_balance(
            apiKey=api_obj.apikey,
            secret=api_obj.secret_key
        )
        return context
    

class DashboardCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.ApiContainer
    form_class = forms.ApiContainerCreateForm 
    template_name = 'tracker_site/dashboard_create.html'
    success_url = reverse_lazy('dashboard_list')

    def form_valid(self, form):
        form = super().get_form(self.form_class)
        instance = form.save(commit=False)
        form.save(False)
        result = bytes(form.cleaned_data['secret_key_text'], encoding='utf-8')
        form.instance.secret_key = CRYPTOGRAPHIC_KEY.encrypt(result) 
        form.save(False)
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class DashboardDeleteView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.DeleteView
):
    model = models.ApiContainer
    template_name = 'tracker_site/dashboard_delete.html'
    success_url = reverse_lazy('dashboard_list')

    def form_valid(self, form):
        messages.success(self.request, _('Container is now deleted.'))
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        api_obj = get_object_or_404(models.ApiContainer, id=self.kwargs['pk'])
        context['container'] = api_obj
        return context
    
    def test_func(self) -> bool | None:
        api_obj = get_object_or_404(models.ApiContainer, id=self.kwargs['pk'])
        return api_obj.user == self.request.user

crypto_tracker/website/templates/tracker_site/chart.html
{% extends 'base.html' %}

{% block content %}
<form enctype="multipart/form-data" method="get">
  
  {% comment %} {% csrf_token %} {% endcomment %}
  <div>
    <label for="id_exchange">Exchange:</label>
    <select name="exchange" id="id_exchange">
    {% for exchange in exchanges %}
      <option value={{ exchange }}>{{ exchange }}</option>
    {% endfor %}</select>
  </div>

  <div id="currenciesField">
    <label for="id_currencies">Currency:</label>
    <select id="id_currencies" name="currencies">
    {% for market in markets_list %}
      <option value={{ market }}>{{ market }}</option>
    {% endfor %}</select>
  </div>
  <button class="button-secondary" type="submit">GO!</button>
  {% if request.GET.tradingview_button == "True" %}
      <a href='#' class="button-secondary" name="tradingview_button" onclick="tradingView(true)">Close Trading view</a>
    {% else %}
      <a href='#' class="button-secondary" name="tradingview_button" onclick="tradingView(false)">Open Trading view</a>
    
  {% endif %}


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    function updateURLParam(param, Value) {
      var url = new URL(window.location.href);
      url.searchParams.set(param, Value);
      history.replaceState(null, null, url.toString());
    }

    $(document).ready(function() {
      var exchangeValue = "{{ request.GET.exchange }}";
      var currenciesValue = "{{ request.GET.currencies }}"
      $("#chartForm").on("submit", function() {
        $("#id_exchange").find("option[value='" + exchangeValue + "']").prop("selected", true); // Set exchange value to empty
        $("#id_currencies").val("");
        
      });
  
      $("#id_exchange").on("change", function() {
        var selectedExchange = $(this).val();
        if (selectedExchange) {
          updateURLParam('exchange', selectedExchange);
          $("#chartForm").submit();
          location.reload();
        }
      });

      $("#id_currencies").on("change", function() {
        var selectedCurrencies = $(this).val();
        if (selectedCurrencies) {
          updateURLParam('currencies', selectedCurrencies);
          $("#chartForm").submit();
          location.reload();
        }
      });

      $("#id_exchange").find("option[value='" + exchangeValue + "']").prop("selected", true);
      $("#id_currencies").find("option[value='" + currenciesValue + "']").prop("selected", true);
    });

    function generateUrl(url, params) {
      var i = 0, key;
      for (key in params) {
          if (i === 0) {
              url += "?";
          } else {
              url += "&";
          }
          url += key;
          url += '=';
          url += params[key];
          i++;
      }
      return url;
  }

    function tradingView(arg) {
      let params = new URLSearchParams(document.location.search);
      var newLocation = "http://localhost/chart/";
      // var csrfmiddlewaretoken = params.get('csrfmiddlewaretoken');
      var tradingViewVar = "{{ trading_view|escapejs }}";
      var exchange = params.get('exchange');
      var currencies = params.get('currencies');
      if (arg) {
        tradingViewVar = "False"
        newLocation = generateUrl("http://localhost/chart/",{ 
          // csrfmiddlewaretoken: csrfmiddlewaretoken,
          exchange: exchange,
          currencies: currencies,
          tradingview_button: tradingViewVar,
      })
      } else {
        tradingViewVar = "True"
        newLocation = generateUrl("http://localhost/chart/",{ 
          // csrfmiddlewaretoken: csrfmiddlewaretoken,
          exchange: exchange,
          currencies: currencies,
          tradingview_button: tradingViewVar,
      })
      
      } 
      window.location.href = newLocation;
    }

  </script>
</form>



{% if request.GET.tradingview_button == "True" %}
<!-- TradingView Widget BEGIN -->
  <div class="tradingview-widget-container" disabled>
      <div id="tradingview_40d3c"></div>
      <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text">Track all markets on TradingView</span></a></div>
      <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
      <script type="text/javascript">
      new TradingView.widget(
      {
      "autosize": true,
      "symbol": "{{ exchange|upper }}:{{ request.GET.currencies|cut:'/' }}",
      "timezone": "Etc/UTC",
      "theme": "dark",
      "style": "1",
      "locale": "en",
      "toolbar_bg": "#f1f3f6",
      "enable_publishing": true,
      "backgroundColor": "rgba(0, 0, 0, 1)",
      "gridColor": "rgba(203, 203, 203, 0.06)",
      "withdateranges": true,
      "range": "1D",
      "hide_side_toolbar": false,
      "allow_symbol_change": true,
      "details": true,
      "hotlist": true,
      "calendar": true,
      "show_popup_button": true,
      "popup_width": "1000",
      "popup_height": "650",
      "container_id": "tradingview_40d3c"
    }
      );
      </script>
    </div>
  <!-- TradingView Widget END -->
{% endif %}

{% endblock content %}

crypto_tracker/website/templates/tracker_site/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class='menu'>
    <ul class='menu-wrapper'>
        <li class='menu-item'><a class="menu-button" href={% url 'dashboard_create' %}>Create new Container</a></li>
    </ul>
</div>
<ul class="articles-wrapper">
    {% if apicontainer_list %}
        {% for container in apicontainer_list %}
            <li class="article-container">
                <a href={% url 'dashboard_detail' container.pk %}>{{ container.name }}</a>
                <p>{{ container.exchange }}</p>
                <p>{{ container.apikey }}</p>
                <p>{{ container.description }}</p>
            </li>
        {% endfor %}
    {% else %}
        <p>:/</p>
    {% endif %}
</ul>

{% endblock content %}

crypto_tracker/website/templates/tracker_site/dashboard_create.html
{% extends 'base.html' %}
{% block content %}

<form enctype="multipart/form-data" method="post" action="{{ request.path }}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm</button>
</form>

{% endblock content %}

crypto_tracker/website/templates/tracker_site/dashboard_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <button type="submit">Confirm Delete</button>
    <a href="{% url 'dashboard_detail' container.id %}">Change my mind</a>
</form>

{% endblock content %}

crypto_tracker/website/templates/tracker_site/dashboard_detail.html
{% extends 'base.html' %}
{% block content %}
{% load website_extras %}
<div class='menu'>
    <ul class='menu-wrapper'>
        {% comment %} <li class='menu-item'><a class="menu-button" href={% url '??' %}>Edit Container</a></li> {% endcomment %}
        <li class='menu-item'><a class="menu-button" href="{% url 'dashboard_delete' api_obj.pk %}">Delete Container</a></li>
        
    </ul>
</div>


{% if api_obj %}
    <p>hello world!</p>
{% endif %}
<div class="exchange-detail-markets-wrapper">
    <h2>coins</h2>
    <h2>equity</h2>
    <h2>walletBalance</h2>
    <h2>h2ositionMargin</h2>
    <h2>availableBalance</h2>
    <h2>orderMargin</h2>
    <h2>unrealisedpnl</h2>
    <h2>RealisedPnl</h2>
</div>
<ul class="exchange-detail-markets-container">
{% for coin_dict in ccxt_obj.info.result.list %}
    <li class="exchange-detail-markets-item-container">
        <p>{{ coin_dict.coin }}</p>
        <p>{{ coin_dict.equity }}</p>
        <p>{{ coin_dict.walletBalance }}</p>
        <p>{{ coin_dict.positionMargin }}</p>
        <p>{{ coin_dict.availableBalance }}</p>
        <p>{{ coin_dict.orderMargin }}</p>
        <p>{{ coin_dict.unrealisedPnl }}</p>
        <p>{{ coin_dict.RealisedPnl }}</p>
    </li>
    {% endfor %}
</ul>

{% endblock content %}

crypto_tracker/website/templates/tracker_site/exchange_detail.html
{% extends 'base.html' %}
{% load website_extras %}

{% block title %}{{ exchange }}{% endblock title %}

{% block content %}
<div class="exchange-detail-wrapper">
    <div class="exchange-detail-container">
        <img src="{{ exchange.get_info.urls.logo }}">
        <h2>{{ exchange }}</h2>
        <a href="{{ exchange.get_info.urls.www }}">{{ exchange }} url</a>
    </div>
</div>



<div class="exchange-detail-markets-wrapper">
    <h2>{{ exchange }} symbols </h2>
    <h2> Price </h2>
    <h2> 1h </h2>
    <h2> Volume </h2>
    <h2> Last 7d </h2>
</div>
    <ul class="exchange-detail-markets-container">

    {% for symbol in markets %}
        <li class="exchange-detail-markets-item-container">
            <p>{{ symbol }}</p>
            <p>{% call_method exchange 'fetch_ohlcv' get="close" symbol=symbol limit=2 %}</p>
            {% call_method exchange 'get_price_change' period=3600000 symbol=symbol %}
            {% comment %} {% call_method exchange 'get_price_change' period=3600000 symbol=symbol %} {% endcomment %}
            {% comment %} {% call_method exchange 'get_price_change' period=86400000 symbol=symbol %} {% endcomment %}
            <p>{% call_method exchange 'fetch_ohlcv' get="volume" symbol=symbol limit=2 %}</p>
            <a href="/chart/?exchange={{ exchange }}&currencies={{ symbol }}">chart</a> {% comment %} {{ market.1h }}, {{ market.1d }}, {{ market.7d }}, {{ market.30d }}, {{ market.365d }} {% endcomment %}
            
        </li>
    {% endfor %}
    
    </ul>


{% endblock content %}

crypto_tracker/website/templates/tracker_site/exchanges_list.html
{% extends 'base.html' %}

{% block title %}Exchanges{% endblock title %}

{% block content %}
<div class='menu'>
    <div class='menu-wrapper'>
        {% if request.GET.sort == "name" %}
            <a class="menu-button" href="?sort=">unsort</a>
        {% else %}
            <a class="menu-button" href="?sort=name">Sort by Name</a>
        {% endif %}
    </div>
</div>


<ul class="exchanges-wrapper">
{% for exchange in exchangemodel_list %}
    <a class="exchange-button" href={% url 'exchange_detail' exchange.slug %}>
        <li class="exchanges-container">
            <p>{{ exchange }}</p>
            <img src="{{ exchange.get_info.urls.logo }}">
        </li>
    </a>
    {% endfor %}
</ul>



{% endblock content %}

crypto_tracker/website/templates/tracker_site/news.html
{% extends 'base.html' %}

{% block content %}

<div class="sort-buttons">
    <a href="?sort=desc">desc</a>
  </div>

<div class="news-upper-container">
    <div class="container">
        <h1 class="news-title">News Flow</h1>
        <p class="news-description">Follow what's happening with real-time updates from around the world.</p>
    </div>

    <form class="search-bar-wrapper" method="get">
        {% csrf_token %}
        <div class="search-bar-container">
            <label for="search">Search: </label><br>
            <input class="search-bar" placeholder="Search something :)" type="search" name="search" value="{{ request.POST.search }}">
            <button class="button-primary" type="submit">GO!</button>
        </div>
        <div>
            <button class="button-secondary" name="search" value="Crypto" type="submit">Crypto</button>
            <button class="button-secondary" name="search" value="Stocks" type="submit">Stocks</button>
            <button class="button-secondary" name="search" value="Forex" type="submit">Forex</button>
            <button class="button-secondary" name="search" value="Futures" type="submit">Futures</button>
            <button class="button-secondary" name="search" value="Indices" type="submit">Indices</button>
            <button class="button-secondary" name="search" value="Bonds" type="submit">Bonds</button>
            <button class="button-secondary" name="search" value="World economy" type="submit">World economy</button>
        </div>
        
    </form>
</div>

<ul class="articles-wrapper">
    {% for article in articles %}
    
    <li class='article-container'>
        <a href="https://{{ article.link }}" alt="Article Image">
            <img src={{ article.img }}>
            {% if article.title|length > 107 %}
                <p>{{ article.title|truncatewords:12 }}</p></a>
            {% else %}
            <p>{{ article.title }}</p></a>
            {% endif %}
        <p>{{ article.datetime }}</p>
        <p>{{ article.date }}</p>
    </li>
    
    {% endfor %}
</ul>

{% endblock content %}